const appsData = [
  {
    id: 'sistema-solar',
    title: 'Sistema solar 3D',
    description: 'Explora y aprende sobre el sistema solar en una experiencia interactiva en 3D.',
    category: 'Biología / Astronomía',
    url: 'https://apps-educativas.com/curso/eso/1/biologia/app/sistema-solar',
    icon: 'globe',
    iconColor: '#61dafb',
    prompts: [
      { id: 1, text: 'Quiero crear una app que sea un simulador del sistema solar.\nDebe ser un campo 3d que ocupe toda la pantalla donde podremos consultar los planetas del sistema solar y los datos de cada planeta, debe ser intuitivo y fácil de utilizar. \nQuiero que utilices animaciones y rotaciones avanzadas para simular el movimiento, y texturas y materiales adecuados para simular la superficie de los planetas' },
      { id: 2, text: 'Cuando hagas clic en un planeta quiero una animación que te acerce al planeta y te permita ver en detalle la superficie y sus características, quiero mejoras en la iluminación y en las texturas de los planetas' },
      { id: 3, text: 'La iluminación no funciona bien, por ejemplo, si me acerco a un planeta haciendo clic sobre él y manteniendome con la parte que de da el sol de frente, en la rotación se hace oscuro, no tiene sentido' },
      { id: 4, text: 'Pero ahora le has quitado las texturas que le daban realismo a los planetas' },
      { id: 5, text: 'Añade un panel de configuración que debe estar visible en todo momento donde podemos configurar la velocidad de rotación de los planetas alrededor del sol, zoom y otros controles que consideres relevantes' },
      { id: 6, text: 'Hay problemas en la descarga de una textura:\n\nUnexpected Application Error!\nCould not load https://upload.wikimedia.org/wikipedia/commons/c/cf/Earthmap1000x500.jpg: undefined\nError: Could not load https://upload.wikimedia.org/wikipedia/commons/c/cf/Earthmap1000x500.jpg: undefined\n    at http://localhost:5173/node_modules/.vite/deps/chunk-K2RYOLCF.js?v=53de3e35:17488:39\n    at HTMLImageElement.onImageError (http://localhost:5173/node_modules/.vite/deps/chunk-5UO5SBPP.js?v=53de3e35:24350:20)\n💿 Hey developer 👋\n\nYou can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.' },
      { id: 7, text: 'Quiero que añadas texturas de alta calidad a los planetas (2K), las puedes descargar de: https://www.solarsystemscope.com/textures/' },
      { id: 8, text: 'Pero no quiero un botón para descargar las texturas, quiero tenerlas guardadas todas de inicio en el proyecto' },
      { id: 9, text: 'Mejora es aspecto gráfico y las animaciones de la app sistema-solar' },
      { id: 10, text: 'El titulo del arriba a la izquierda no lo quiero.\nAñade un cada planeta y el sol un nuevo punto en forma de estrella, ese punto deberá abrir un modal con un video de youtube incrutado de foma original y debe estar relacionado con el planeta en particular o con una temática similar del universo, los videos debes sacarlos siempre del canal: https://www.youtube.com/@kurzgesagt_es' },
      { id: 11, text: 'No se visualiza el reproductor de youtube por algún motivo, además quiero que el modal con el video esté completamente por encima sin que se vean los elementos del sistema solar, para optimizar puedes parar todas las animaciones y así ver el video consumiendo los mínimos recursos posibles' },
      { id: 12, text: 'Sigue sin verse el video, me aparece el siguiente error en el navegador:\nSpecify a Cross-Origin Embedder Policy to prevent this frame from being blocked\nBecause your site has the Cross-Origin Embedder Policy (COEP) enabled, each embedded iframe must also specify this policy. This behavior protects private data from being exposed to untrusted third party sites.\n\nTo solve this, add one of following to the embedded frame’s HTML response header:\n\nCross-Origin-Embedder-Policy: require-corp\nCross-Origin-Embedder-Policy: credentialless (Chrome > 96)\n1 request\nRequest\tParent Frame\tBlocked Resource\n\noHg5SJYRHA0?autoplay=1&rel=0\t\nhttp://localhost:5173/curso/eso/1/biologia/app/sistema-solar\t\nhttps://www.youtube.com/embed/oHg5SJYRHA0?autoplay=1&rel=0\nLearn more: COOP and COEP' },
      { id: 13, text: 'En la app del sistema solar quiero hacer varias modificaciones:\n*No se debe configurar el tamaño de los planetas, modifica ese slider por velocidad de rotación del planeta\n*La parte de configuración no queda bien el estilo del slider tan claro\n*Debes poder pulsar sobre el botón "Configuración" y así mostrar/ocultar los controles de las velocidades y demás\n*El espacio del canvas principal del universo debe ocupar el 100% del espacio disponible de la ventana, tanto en vertical como en horizontal' },
      { id: 14, text: 'no veo el botón de configuración, y no ocupa el 100% de la pantalla el universo, para ello debes modificar parte del contenedor externo al igual que en otras apps, para ello debes revisar AppRunnerPage.jsx también y así lo entenderás mejor todo' },
      { id: 15, text: 'Haz las orbitas y los tamaños de los planetas más realistas, aplica la textura del sol y de los anillos de saturno con las texturas disponibles en la carpeta' },
      { id: 16, text: 'Haz las orbitas y los tamaños de los planetas más realistas, aplica la textura del sol y de los anillos de saturno con las texturas disponibles en la carpeta' },
      { id: 17, text: 'La textura de los anillos de saturno no está bien aplicada, revisa bien la forma de aplicarla' },
      { id: 18, text: 'Añade la luna, y responde siempre en español' },
      { id: 19, text: 'No veo la luna' },
      { id: 20, text: 'Sigo sin ver la luna' },
      { id: 21, text: 'No funciona nada, pantalla con el error  solarSystemData.js:158 Uncaught ReferenceError: neptuneTexture is not defined\n    at solarSystemData.js:158:21' },
      { id: 22, text: 'La luna rota super rapido sobre la tierra, no funciona bien' },
      { id: 23, text: 'La linea de la orbita de la luna no está bien, además quiero que rote más poco a poco respecto a la tierra y también quiero poder pulsar sobre ella para verla' },
      { id: 24, text: 'la linea de la orbita de la luna respecto a la tierra no esta bien, la orbita no se debe mover del centro de la tierra en este caso' },
      { id: 25, text: 'Al pulsar sobre la luna también se debe detener para observala mejor como el resto de planetas, y la iluminación también debe ser coherente' },
      { id: 26, text: 'quiero que añadas la opción de acercarse alejarse y que se mantenga en esa escala\nquiero que el mensaje "Haz clic en un planeta para viajar a él" esté en el menú de configuración\nquiero que el menú sea más coherente visualmente con el resto de la app' },
      { id: 27, text: 'El estilo del menú de configuración te he dicho que lo quiero distinto' },
    ]
  },
  {
    id: 'mesa-crafteo',
    title: 'Mesa de crafteo',
    description: 'Aprende los elementos y combinaciones en física como si fuera un juego.',
    category: 'Física',
    url: 'https://apps-educativas.com/curso/eso/1/fisica/app/mesa-crafteo',
    icon: 'lightbulb',
    iconColor: '#fbbf24',
    prompts: [
      { id: 1, text: 'Crea una app llamada Mesa de Crafteo que será un entorno 3D, debe tener un panel lateral a la derecha con una cuadrícula de elementos de la tabla periódica (H, O, C, N, etc.). El espacio principal debe ser un canvas 3D donde puedo hacer clic para colocar átomos seleccionados como esferas 3D.' },
      { id: 2, text: 'Añade un sistema de enlaces. Los átomos deben tener "puertos" o puntos de conexión. Al hacer clic en el puerto de un átomo se debe crear un enlace  con el elemento seleccionado' },
      { id: 3, text: 'Al intentar enlazar dos átomos, me salta el siguiente error en la consola y la app se queda en blanco:\nTypeError: Cannot read properties of undefined (reading \'position\') at createBond\nsolucionalo' },
      { id: 4, text: 'El error de los enlaces está arreglado, pero los cilindros que conectan los átomos no se orientan correctamente ni tienen la longitud adecuada de un átomo a otro. A veces apuntan a cualquier lado' },
      { id: 5, text: 'Añade en la parte inferior un botón "CRAFTEAR". Arriba añade un contador de "Composición Actual" que liste todos los átomos que hay colocados en el escenario' },
      { id: 6, text: 'Añade una lista de moléculas objetivo (ej. H2O, CO2, NH3). Muestra un apartado de "Objetivo Actual" indicando qué molécula construir' },
      { id: 7, text: 'Al pulsar "CRAFTEAR", valida si el modelo tridimensional de la mesa (cantidad de átomos y enlaces) coincide con el objetivo actual. Si es correcto, muestra un modal de "Síntesis Exitosa" con información de la molécula' },
      { id: 8, text: 'La validación falla siempre. Aunque haga el agua (H2O) con dos hidrógenos y un oxígeno, me dice que es incorrecta porque el orden en el que conecté los enlaces parece importar en tu código. Revísalo para que valide solo por átomos y conexiones sin importar el orden exacto en el que hice clics' },
      { id: 9, text: 'Añade ayudas en la barra inferior: Un botón "Revelar Fórmula" y un botón "Ver Solución" que borra la mesa y construye automáticamente la molécula correcta mediante animación' },
      { id: 10, text: 'La animación de "Ver Solución" ocurre de golpe, añade un efecto entre cada aparición de átomo y enlace para que se vea progresivamente cómo se construye' },
      { id: 11, text: 'En el menú lateral, añade los botones "Recetario" (abre lista de moléculas) y "Tabla" (abre una Tabla Periódica interactiva)' },
      { id: 12, text: 'La Tabla Periódica se superpone mal con el canvas 3D (el canvas se pinta por encima del modal de la tabla). Tienes un problema de z-index, arréglalo para que la tabla esté siempre por encima' },
      { id: 13, text: 'No me termina de convencer la tabla periódica, añade toda la información que puedas de cada elemento, debe ser visible a través de tooltips al pasar el ratón por encima de cada elemento' },
      { id: 14, text: 'Incluye un botón de "Modo Examen" en el lateral. Permite seleccionar dificultad (Fácil, Medio, Difícil). Al iniciar el examen, se ocultan las ayudas y obligas al alumno a construir moléculas consecutivas para obtener puntuación final' },
      { id: 15, text: 'Cuando termino la primera molécula en Modo Examen y le doy a "siguiente molécula", hay un bug: el contador de composición no se reinicia y me cuenta los átomos de la molécula anterior sumados a la nueva' },
      { id: 16, text: 'Para finalizar, añade un tutorial al inicio que enseñe paso a paso cómo colocar un átomo y enlazarlos mediante puertos. Ofrécele algo de físicas divertidas a los átomos y añade efectos de chispas o partículas al tener una síntesis exitosa' },
      { id: 17, text: 'Hay un bug grave: si borro un átomo de la mesa usando el botón de Deshacer o la papelera, el cilindro del enlace químico que conectaba a ese átomo se queda flotando en el espacio 3D apuntando a la nada' },
      { id: 18, text: 'El renderizado 3D va lentísimo. Mejora la optimización de la app para que consuma menos recursos y funcione fluidamente en todo tipo de dispositivos' },
      { id: 19, text: 'Me parece molesto un comportamiento en UI móvil: Al intentar rotar la cámara 3D deslizando el dedo, a veces en lugar de rotar la vista, arrastro accidentalmente un átomo. Configura los controles de OrbitControls para que no haya conflicto (bloquea el panning o el drag al tocar un átomo)' },
      { id: 20, text: 'No me gusta el color de los átomos, cámbialos por colores más vivos' },
      { id: 21, text: 'He detectado un bug: cuando resuelvo una molécula y me aparece el mensaje de "Síntesis Exitosa", se queda pillado y no puedo hacer nada más. Arréglalo' },
      { id: 22, text: 'Añade más moléculas para poder craftear' },
      { id: 23, text: 'El panel inferior quiero tenerlo completamente centrado' },
      { id: 24, text: 'Hay contenedores que se superponen unos con otros, mejora la UI para que no se solapen' }

    ]
  },
  {
    id: 'celula-animal',
    title: 'La célula animal',
    description: 'Anatomía y características de la célula animal en profundidad.',
    category: 'Biología',
    url: 'https://apps-educativas.com/curso/eso/1/biologia/app/celula-animal',
    icon: 'dna',
    iconColor: '#f43f5e',
    prompts: [
      { id: 1, text: 'Crea una app interactiva sobre La Célula Animal. La vista principal debe contener un dibujo svg de alta calidad de una célula animal con todos los orgánulos. Crea un dock inferior horizontal con iconos o emojis para los orgánulos clave. Quiero una app compacta y lista para utilizar abriendo el html, sin utilizar ningún framework adicional, solo html, css y js puros' },
      { id: 2, text: 'En la parte superior, añade una barra de navegación con un selector para 3 modos: "Explorar", "Test" y "Reto". A su derecha, un indicador de progreso con la cantidad de orgánulos explorados' },
      { id: 3, text: 'Implementa "Explorar": Al pasar el ratón por los iconos del dock, el orgánulo correspondiente en la imagen de la célula debe resaltarse con un efecto de brillo. Además, aparece una etiqueta flotante, quiero animaciones originales y elegantes' },
      { id: 4, text: 'Al hacer zoom en la célula no se ve bien el orgánulo, cambia el diseño para que se vea mejor, mira bien la posición de los orgánulos porque se mueven al hacer zoom' },
      { id: 5, text: 'Crea un Panel Lateral Derecho de Información. Al pinchar un orgánulo muestra Título, un "Mote" descriptivo y tres partes: Funciones, Estructura y ¿Sabías que...?' },
      { id: 6, text: 'El texto de la pestaña no carga correctamente, revisa el código' },
      { id: 7, text: 'Desarrolla el modo "Test". La app oculta el panel lateral y lanza un cartel: "ENCUENTRA: [Nombre de Orgánulo]". El usuario debe hacer clic en el orgánulo correcto de la ilustración. Da feedback visual (acierto o error) y lleva una puntuación de los intentos' },
      { id: 8, text: 'En el modo Test, si pulso mal sobre el dibujo me selecciona el div contenedor de fondo o la capa transparente y me da por malo cada clic suelto que hago, incluso fuera de la célula. Limita los áreas clicables estricta y únicamente a las siluetas SVG de los orgánulos' },
      { id: 9, text: 'Implementa el modo "Reto". Un minijuego donde pongo a prueba mi memoria: dos columnas, a la izquierda iconos y nombres de orgánulos y a la derecha definiciones mezcladas. Un botón "Corregir" al final. Selector de dificultad (Fácil 6, Normal 9, Difícil 12)' },
      { id: 10, text: 'Tengo un problema enorme de usabilidad: el arrastrar y soltar del modo Reto no funciona bien en pantallas táctiles, los elementos se quedan pegados' },
      { id: 11, text: 'Añade un "Modo Oscuro" (Dark mode) global de la UI que aplique un sombreado y resalte los colores neón y las etiquetas de la célula para darle un ambiente celular mucho más realista de laboratorio' },
      { id: 12, text: 'He notado que la transición entre "Test" y "Reto" deja restos viables en consola de intervalos corriendo o estados anteriores guardados' },
      { id: 13, text: 'Ahora sí va bien, pero quiero que las partículas de fondo o algunas pequeñas de los orgánulos tengan ligeras animaciones constantes. Agrega eso para que parezca que la célula está viva' },
      { id: 15, text: 'Todo funcionando bien, dale un último repaso a la paleta de colores del dock para que los orgánulos destaquen mejor sobre el fondo oscuro' },
      { id: 16, text: 'He notado que cuando abro el panel derecho lateral para leer la información y luego hago clic en el menú superior para ir a "Test", el panel lateral sigue abierto tapando media pantalla. Haz que el panel se cierre automáticamente al cambiar de modo de juego en la barra de navegación superior' },
      { id: 17, text: 'Tngo un problema en móviles pequeños. La botonera inferior (dock) con los 12 orgánulos no cabe en la pantalla. Haz que el dock sea scrollable horizontalmente ocultando el scrollbar, o reduce su tamaño dinámicamente según el tamaño de la pantalla' },
      { id: 18, text: 'La versión de Reto quiero que mejores la UI para que sea más atractivo visualmente' },
      { id: 19, text: 'Quiero la persistencia del contador "0/12 explorados". Si recargo la página, el contador vuelve a cero y no me guarda qué partes había visitado ya. Quiero que utilices la forma más óptima de implementarlo' }
    ]
  }
];

window.appDataList = appsData;
